### ISSUE TITLE
Reduce misuse of "Deny" button during onboarding

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1816] opened 2019-01-28 15:46 UTC
We've learned from [previous testing](https://github.com/blockstack/blockstack-browser/issues/1775#issuecomment-452336477) that users accidentally select "Deny" during onboarding when they actually intend to grant permission to an app and use it.

This issue entails improving the design of the deny button to reduce accidental clicks.

**Comment by markmhx** [comment] 2019-01-28 15:47
@aulneau Could you help me design for this issue during this sprint?

**Comment by jeffdomke** [comment] 2019-01-28 17:54
There is already a solution in the figma, been there since maybe Oct? And the problem isn't the button (although we should change it) the problem is that deny routes back to the browser when it should allow the user to recover in some more graceful way.

**Comment by jeffdomke** [comment] 2019-01-28 22:01
![screen shot 2019-01-28 at 4 38 28 pm](https://user-images.githubusercontent.com/767828/51869309-2ea3f980-231e-11e9-9bd6-ed4a34d7d2aa.png)

Found the solution I mentioned. 

`Deny` has been changed to `Cancel` 

Instead of returning to browser it just returns to the previous screen, where the user will figure out they need to move forward if they want to access the app.

**Comment by markmhx** [comment] 2019-01-29 13:13
This design change looks good to me. I like how subtle "Cancel" is up there.

If I'm authenticated with the Browser already, I'm finding that the "Select an ID" modal shows up first after choosing to authenticate from the App:

<img width="511" alt="screen shot 2019-01-29 at 14 10 34" src="https://user-images.githubusercontent.com/28991/51910508-b564df00-23cf-11e9-8c58-0bb658a8cb56.png">

In that case, there's no previous state to which we can direct the user when they select "Cancel". Perhaps we ought to just universally kick the user back to the app's URL from which they were referred if they choose this option? That way they can enter the auth flow from there again if desired.

I think that's in line with what you're recommending. Only difference may be that in the "new user" flow case, we direct the user straight back to the app instead of the modal shown on the left of the mockup above ("Your ID is ready...").

**Comment by moxiegirl** [comment] 2019-02-18 15:17
Ran into a version of this when testing the Gai hub onboarding.  

1. Click on *Sign in on Blockstack* from a DApp configured to solicit a Gaia hub url.
    Routed to browser and this screen displayed.

![image](https://user-images.githubusercontent.com/1347209/52959866-39b1de80-334c-11e9-82cd-b00ce1254d96.png)

At this point, I wanted to *choose another id* --- I think we used to actually _have that option_. in an old version of the flow. Anyway, at that point, I selected *Deny* thinking I would then be offerred the choice to pick another ID or create a new one.

Instead, I was returned to the home page of the Blockstack browser.

Cognitively, I was thinking **Deny** use of Moxiegirl and choose another. Really, what this was saying **Deny Hello Blockstack access**.  But at that point, I was focused on my task and the relationship between where I starte, my DApp Hello Blockstack, and the onboarding was unclear.

What should happen, when a user selects **Deny** we need to clarify what the user is denying and _return them to the requesting application_ not to the Browser.  Or put up a dialog up explaining what happened in the browser. Something...

**Comment by markmhx** [comment] 2019-02-18 16:01
@moxiegirl thanks for the detailed report 🙏

**Comment by markmhx** [comment] 2019-03-10 16:21
@hstove I'm assigning this to you for the sprint starting tomorrow. Can you take a look and let me know if the design guidance is missing anything from your perspective or ready to integrate?

**Comment by moxiegirl** [comment] 2019-03-11 23:30
Just going to leave this here...I think the Application name should be in bold not quotes -- it is getting lost --- the eye is drawn to the bold. Also, the title of the dialog is wrong, this is about Granting access, selecting an ID is _secondary_ action.

![image](https://user-images.githubusercontent.com/1347209/54164745-0af2c980-441b-11e9-9280-fc9aad7b69ac.png)

**Comment by markmhx** [comment] 2019-03-12 09:30
@moxiegirl I think this are good ideas but best to tackle in a separate issue since we want to expedite this one for a pretty specific reason (helping users from accidentally clicking "deny" in the current implementation). Mind creating another issue and cross-linking here?

**Comment by moxiegirl** [comment] 2019-03-12 17:44
@markmhx will do.

**Comment by aulneau** [comment] 2019-04-01 14:30
So I have this fixed in a local branch. I think the best behavior we can hope for is when a user his cancel, it will close that window. For any auth attempt, the default behavior is such that it opens a new window/tab, thus not having any history to push the user back to. When the tab closes, they will be found with whatever screen they had been on previously. If however they are authing from the sign in process, I think cancel could do one of two things: close the window because it will still bring them to the app they started in, or bring them to the browser homepage as this might be their first time in the app. cc @markmhx

**Comment by markmhx** [comment] 2019-04-01 14:54
@aulneau How does the "Deny" currently work? It sends them to the browser homepage, right?

I'm not too concerned about changing the redirect behavior in this issue, since denying / canceling is a pretty tertiary flow at this point. But, happy to do so if you think it's relatively easy to tackle.

If we do close the window upon cancelation, are there any cases in which the browser didn't actually open in a new window originally? And so we may be closing the user out of their only browser tab?

**Comment by aulneau** [comment] 2019-04-01 15:10
Yes so typically it would be a user is in 'app a', they'd hit sign in, a new window would open (or tab), and they would hit deny which would bring them to the browser homepage, which they might not have ever been on. Where as with my new update, it would just close the newly opened tab and bring them back to the app they were using. I would suggest we do that instead of redirecting the user to the app url because then it would start a loop of new tabs with the same url but different states. 

Realistically this bring us towards a space in which the new tab/window that the auth is in could feel more like an oAuth experience. eg a smaller window that is only open to auth and then closes when finished.

**Comment by aulneau** [comment] 2019-04-01 15:11
additionally it might not be super straightforward to always get the app url to send them back to.

**Comment by aulneau** [comment] 2019-04-01 15:14
> If we do close the window upon cancelation, are there any cases in which the browser didn't actually open in a new window originally? And so we may be closing the user out of their only browser tab?

I believe it is _always_ a new window or tab, unless someone just goes to browser.blockstack.org, but at that point, they could never auth from the sign in flow.

**Comment by jeffdomke** [comment] 2019-04-01 22:52
@aulneau think I finally get all the complexity here. Want to help, but I'm not sure writing out a bunch of abstract paragraphs will cut it. Anyway you can demo your latest thinking, even if just on your local?

**Comment by markmhx** [comment] 2019-04-02 11:31
Just to note that @aulneau I think you mentioned yesterday that since posting the above comments, you realized there are cases in which we load the browser in the same window as the application upon hand-off. So, if we add a case in which we close the browser window upon cancellation, we'd want to ensure that a new window was indeed created upon hand-off and apply that behavior only in that case, not the one in which a new window was not created upon hand-off.

**Comment by aulneau** [comment] 2019-04-02 13:41
@markmhx yes that is correct. For a non-local browser installation, eg someone who only uses browser.blockstack.org, the auth will happen within the same tab.

@jeffdomke yeah I am working on a solution to demo, I can send a link/video/gif later today that should demo the functionality for the two use cases.

This is what I plan on it doing:

Case 1 - user has browser locally installed. Anytime an auth happens, it happens in a new tab. The deny(cancel) button will close the tab every time.

Case 2 - user only uses hosted browser. We could cache the referrer (app link) and send them back to the url they came from when they hit cancel.

Case 3 - mobile sdk users. I am not 100% positive, but I believe it would act like case 1. cc @yknl

**Comment by yknl** [comment] 2019-04-02 14:08
On mobile the deny button sends the user to the Browser home page right now. It would be difficult to make the the deny button redirect back to the app. You would have to send the user to the `redirect.html` page, which needs to be modified to work without a valid auth response. And developers need to modify their app to handle that. I suggest removing the deny button in mobile. There are native back buttons on both Android and iOS that will work better.

**Closed** 2019-05-03 17:13 UTC
Labels: enhancement
