### ISSUE TITLE
"Add Username to Profile" creates username separate from profile

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#522] opened 2017-06-05 19:25 UTC
In testing portal on regtest (testing now on production -- will let you know once the profile registration finishes), I discovered the following issue: 

When I add a username to my created profile, and the username eventually appears in the browser, there now appear _two_ profiles -- one empty one corresponding to my registered name, and the previous one with a "hash name."

In attempting to run down the bug, I found that `createNewIdentityFromDomain` should be getting a `addingUsername` parameter, but wasn't receiving it. This commit has the change:

https://github.com/kantai/blockstack-portal/commit/84f86d051334285c79adc14c01344a6a0054ae99

But _anyways_ that doesn't fix the problem either.

**Comment by larrysalibra** [comment] 2017-06-16 04:26
The problem is that we're using the owner address as the domain before a name is registered. When we find a name owned by one of the addresses in our wallet, we should first check if there's an existing local identity entry for the name stored with the owner address as a key and if so, copy it to an entry using the domain name as key and remove the original.

**Comment by larrysalibra** [comment] 2017-06-20 19:12
Should be fixed now.

**Closed by larrysalibra** 2017-06-20 19:12 UTC
Labels: 2 hours, bug
