### ISSUE TITLE
fix the bug where creating a new ID copies the profile of the previous ID

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#1040] opened 2017-11-07 16:45 UTC
I can provide a video if you'd like.

**Comment by larrysalibra** [comment] 2017-11-07 17:13
Video along with steps to reproduce would be great!

**Comment by larrysalibra** [comment] 2018-01-17 13:20
@shea256 do you still have video of this?

**Comment by wbobeirne** [comment] 2018-08-02 15:11
Looks like this was fixed with the above commit.

**Closed by wbobeirne** 2018-08-02 15:11 UTC
Labels: bug
