### ISSUE TITLE
Choose your storage provider page during onboarding flickers

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#926] opened 2017-10-16 22:23 UTC
The “choose your storage provider” on-boarding panel flickers after you choose default storage.

**Comment by larrysalibra** [comment] 2017-10-18 04:52
Closing this as a duplicate of https://github.com/blockstack/blockstack-browser/issues/875

@yknl Let me know if it's describing something else.

**Closed by larrysalibra** 2017-10-18 04:52 UTC
