### ISSUE TITLE
After signup in firefox: `username: null` after first login to an app

### ISSUE THREAD

**Issue by bodymindarts** [blockstack/blockstack-browser#1472] opened 2018-06-25 18:16 UTC
Over the weekend a number of users experienced the following:

- signup for a new id in firefox
- login to an app
- username that the app receives is `null` (nameless user) even though the username is displayed in the browser correctly.

For Id's that have been confirmed this doesn't seem to be an issue. Just when the 'instant lookup' is happening.

**Comment by aulneau** [comment] 2018-06-25 18:29
Thanks for posting this. This might have to do with something we added to send the username along with the auth request for names that are not fully propagated. 

We will take a look at this! cc @yknl

**Comment by kantai** [comment] 2018-06-25 22:58
I think this was caused by an encoding bug in blockstack-core (causing the instantaneous subdomain resolution to intermittently 500), this was addressed in https://github.com/blockstack/blockstack-core/pull/838 and that patch was rolled out.

**Closed** 2019-01-22 18:53 UTC
Labels: bug
