### ISSUE TITLE
Issue logging in to Blockstack apps

### ISSUE THREAD

**Issue by jay-hwang** [blockstack/blockstack-browser#735] opened 2017-09-06 23:03 UTC
Ran into this error when trying to log into Blockstack apps:

```
main.js:3403 Uncaught TypeError: Cannot read property 'appsNodeKey' of undefined
    at AuthModal.login (main.js:3403)
    at Object.invokeGuardedCallback (main.js:125273)
    at executeDispatch (main.js:119310)
    at Object.executeDispatchesInOrder (main.js:119330)
    at executeDispatchesAndRelease (main.js:118741)
    at executeDispatchesAndReleaseTopLevel (main.js:118752)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (main.js:130661)
    at Object.processEventQueue (main.js:118952)
    at runEventQueueInBatch (main.js:125340)
```

@kantai suggested wiping localStorage and re-initializing Blockstack Browser so I ran `localStorage.clear()` in the browser console, deleted my Blockstack browser account and restored an account with a username `ithiel.id`. After connecting my Gmail and Dropbox, it created a new profile with no username instead of restoring, but I was able to log in to Blockstack Apps using the throwaway profile.

Hoping the persistent issue was resolved, I tried restoring `ithiel.id` profile. It restored successfully but I was now unable to log in to Blockstack apps with both 'ithiel.id' and the throwaway profile. Then returns the same dreadful error: 

```
main.js:3403 Uncaught TypeError: Cannot read property 'appsNodeKey' of undefined
    at AuthModal.login (main.js:3403)
    at Object.invokeGuardedCallback (main.js:125273)
    at executeDispatch (main.js:119310)
    at Object.executeDispatchesInOrder (main.js:119330)
    at executeDispatchesAndRelease (main.js:118741)
    at executeDispatchesAndReleaseTopLevel (main.js:118752)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (main.js:130661)
    at Object.processEventQueue (main.js:118952)
    at runEventQueueInBatch (main.js:125340)
```

I believe @jackzampolin ran into the same error earlier today. Maybe he can provide some more detail

**Comment by jackzampolin** [comment] 2017-09-07 03:54
This is a duplicate of https://github.com/blockstack/blockstack-browser/issues/734. Closing and linking this in the other issue. Thanks for the report!

**Closed by jackzampolin** 2017-09-07 03:54 UTC
