### ISSUE TITLE
Nameless user on restore

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1431] opened 2018-05-31 18:11 UTC
![Screen Shot 2018-05-31 at 6:11 PM](http://marker.screenshots.prod.s3.amazonaws.com/7a2ae1c908e64eeb93df4b59f372c0cf-1527790275130.png)

Checked – this is showing 'nameless user' even when the name 
shows up in /profiles. Should display the proper ID. 

---
### More Info

**Source URL**: [https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in](https://deploy-preview-1268--reporter-beaver-73821.netlify.com/sign-in)

**Comment by yknl** [comment] 2018-05-31 22:00
Related to this https://github.com/blockstack/blockstack-browser/issues/1355 It's something we can fix this in the next release.

**Comment by yknl** [comment] 2018-06-20 19:52
This issue is a duplicate of https://github.com/blockstack/blockstack-browser/issues/1355

**Closed by yknl** 2018-06-20 19:52 UTC
Labels: bug, enhancement

**Comment by aulneau** [comment] 2018-06-21 16:01
should be fixed with https://github.com/blockstack/blockstack-browser/commit/7cdbc12d1892f7a53c4637092f6906d33cd944e9
