### ISSUE TITLE
create design requirements for the registration process

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#370] opened 2017-04-03 17:41 UTC

**Comment by pstan26** [comment] 2017-04-04 19:08
Once you register a name, add messaging about keeping your computer on.
![screen shot 2017-04-04 at 2 52 32 pm](https://cloud.githubusercontent.com/assets/5605552/24674162/8454251c-1948-11e7-9758-88b325b5fd68.png)

**Comment by shea256** [comment] 2017-04-04 19:09
@pstan26 @larrysalibra @jcnelson What's the best way we can avoid requiring the users to keep their computers on?

**Comment by larrysalibra** [comment] 2017-04-04 19:36
@shea256 
> What's the best way we can avoid requiring the users to keep their computers on?
Generate and sign all of the transactions, broadcast the 1st and send the others to a trusted server to queue and send out at the appropriate time.

**Comment by larrysalibra** [comment] 2017-04-04 19:39
@shea256 

We could also have two methods of registering:

1) the current method - you can't turn your computer off
2) via a 3rd party registrar: you'd buy your name from them with bitcoin (or an alternate payment method). You'd trust them to actually transfer the name to your address.

**Comment by pstan26** [comment] 2017-04-04 23:19
@larrysalibra My input is that a 3rd party registrar is not a viable option short term option at the moment. 

What are the drawbacks to "Generate and sign all of the transactions, broadcast the 1st and send the others to a trusted server to queue and send out at the appropriate time."? At first glance it sounds like a nice solution.

**Comment by larrysalibra** [comment] 2017-04-05 11:30
@pstan26 
> What are the drawbacks to "Generate and sign all of the transactions, broadcast the 1st and send the others to a trusted server to queue and send out at the appropriate time."? At first glance it sounds like a nice solution.

We need to create that server, set it up, run it and figure out how it interacts with Portal.

I'd say it's not trivial. @jcnelson would be in a better position to tell us how hard it would be.

From my point of view, I don't think a 3rd party registrar is that much work. Then again I've been handling payments online for a decade.

**Comment by larrysalibra** [comment] 2017-04-05 11:36
Interestingly, on macOS at least, they seem to have gotten more aggressive about putting the computer to sleep even when plugged in:

<img width="670" alt="screen shot 2017-04-05 at 7 31 11 pm" src="https://cloud.githubusercontent.com/assets/597182/24703677/c8eff1d0-1a36-11e7-8365-a4c1caf6d5e5.png">

It used to have a slider that by default didn't go to sleep when idle for while when plugged in.

It looks like we can programmatically prevent it from sleeping: https://developer.apple.com/library/content/qa/qa1340/_index.html

**Comment by pstan26** [comment] 2017-04-05 14:20
> From my point of view, I don't think a 3rd party registrar is that much work. Then again I've been handling payments online for a decade.
Yea its not so much the integration but partnership coordination and unknown time to close a partner (assuming you mean integrating with a domain registrar like gandi.net or something).

**Comment by larrysalibra** [comment] 2017-04-05 20:36
# Registration process improvement reqs:

**_We need to:_**

1. **Make sure the user knows:**
	* She has to pay for the name in Bitcoin
	* Roughly how much Bitcoin names cost. (This varies by length of name and characters they contain, bitcoin network fees, certain characteristics about their address so we can't provide an exact amount until they have their bitcoin in their wallet and are about to click register)
	* That she will have to keep her computer on for several hours after clicking register 
	* What a name is and what it gets you.

2. Indicate whether or not the user has enough Bitcoin in his wallet. 
 	* If there isn't enough Bitcoin, disable the registration process, and prompt the user to send bitcoin to her wallet. We could show an address and possibly a QR code to make it quick and easy.

3. As the user types, we can check:
	* if a name is available, and..
	* if it is, we can display the price to register it. 
	* We should indicate if a name is unavailable
 	* if the user's wallet doesn't have enough money for a particular name.

4. Display errors that come back from Core. Core may decide that the user's wallet still doesn't have enough money in which case we should show an interface similar to 2.
5. After registration is successfully submitted, we should help the user create a new profile.

I think we can get away with sending the user to the "edit profile" page after a successful registration. 

-- 
It would be helpful in terms of managing user expectations (it's not doing anything!) to indicate the progress of the registration to the user.

There are essentially five states after the user clicks register. (w

1. pre-order sent 
2. register sent 
3. update sent 
4. transfer sent
5. name available for use by user

Currently, there are a few hours between each step. 

We could create a "pending registrations" page that shows each name and where it is in the registration process and then send users there when they click on a "pending". We could also add an icon or message in the status bar to indicate they have pending registrations.

Thoughts? @guylepage3 @shea256

**Comment by larrysalibra** [comment] 2017-04-26 09:24
pinging @shea256 @guylepage3 about this issue

**Comment by guylepage3** [comment] 2017-05-01 14:59
@shea256 we're going to move this issue over to your plate for this week. I'll follow up after you do a quick and dirty on this.

**Comment by guylepage3** [comment] 2017-07-19 14:42
@shea256 @larrysalibra are we going to push this task off?

**Comment by larrysalibra** [comment] 2017-07-24 10:14
@guylepage3 yes. pushing this off.

**Comment by larrysalibra** [comment] 2017-08-03 01:38
@shea256 @guylepage3 

I've taken a stab at some wireframes of a new name registration flow:

It's 3 pages:

1. Select name
2. Confirm or deposit funds (confirm when funds are already available or not needed)
3. status page: after registration is sent, the user ends up on a new name status page that shows the registration status of any names that have pending registration tasks

I've sketched two different options for step one: email-style and domain-style. I prefer the domain name style.

Please take a look at this PDF for the sketches: 

 [Blockstack Name Registration Flow.pdf](https://github.com/blockstack/blockstack-browser/files/1195729/Blockstack.Name.Registration.Flow.pdf)

One issue I haven't addressed is the issue of multiple underlying blockchains (eg. bitcoin and ethereum). Happy to discuss ways that we can indicate future support for those.

Look forward to your feedback!

**Comment by guylepage3** [comment] 2017-08-03 01:46
@larrysalibra Awesome! Can you just upload the flow as images so that others in the community can quickly see the flow without downloading a PDF?

**Comment by larrysalibra** [comment] 2017-08-03 02:33
![img_0033](https://user-images.githubusercontent.com/597182/28903372-19459f82-7837-11e7-8830-d52f183acb50.PNG)
![img_0035](https://user-images.githubusercontent.com/597182/28903374-19491f2c-7837-11e7-84c8-6a072ef5208e.PNG)
![img_0036](https://user-images.githubusercontent.com/597182/28903373-194845de-7837-11e7-9a58-927d3036918b.PNG)
![img_0037](https://user-images.githubusercontent.com/597182/28903375-196c422c-7837-11e7-81d3-74d93c0f9d60.PNG)
![img_0038](https://user-images.githubusercontent.com/597182/28903376-197015dc-7837-11e7-91d0-110e290ff6df.PNG)
![img_0039](https://user-images.githubusercontent.com/597182/28903377-1977d920-7837-11e7-8c45-756dd9c1e76a.PNG)
![img_0034](https://user-images.githubusercontent.com/597182/28903378-1989fe3e-7837-11e7-9286-2bc217cef799.PNG)

**Comment by shea256** [comment] 2017-08-03 17:39
@larrysalibra Beautiful! Very well done and very well thought out. Super excited for this.

I really like the domain name style on page 1. I also like both versions of the payment page for page 2. Page 3 looks nice and I like the color indicators a lot. That said, I do believe it would be better to convey the process with a progress bar as opposed to what looks like tabs.

To me, it seems like the next step is to see how these screens integrate into the rest of the app and how you navigate back at any point in time. We should think hard about this in terms of the new mobile-style screen size that we're moving to.

**Comment by guylepage3** [comment] 2017-08-03 18:49
@larrysalibra great work here. 😄 

Page 1
- I personally like the email style as there is less on the page
- I would also like to see the TLD to be below the name input field as a pulldown. Then when the user chooses a TLD it updates in the name field. I would also make the choosing of the TLD a mandatory item.

*Side note – One way to make it feel like the user is going through less steps is to "bundle" or consolidate steps into screens. For example, combining two mandatory selections into one screen instead of two. Been noticing that it's a better experience, albeit not the "best," than jumping to new screen, new screen, new screen, etc...

Page 2
- I would like to see the word "Confirm" somewhere in the button.. "Confirm Purchase." After all it is a confirmation modal.

>Page 3 looks nice and I like the color indicators a lot. That said, I do believe it would be better to convey the process with a progress bar as opposed to what looks like tabs.

I agree with @shea256 on this one.

**Comment by larrysalibra** [comment] 2017-08-03 20:47
> Page 3 looks nice and I like the color indicators a lot. That said, I do believe it would be better to convey the process with a progress bar as opposed to what looks like tabs.

I agree - tabs aren't ideal.  The problem i was trying to solve is that there are ~8 different states in the name purchase process for a regular (non-subdomain name) and it's hard to provide much in the way of information about which steps have completed versus which are remaining. We, of course, don't have to do that: we could have a progress that just lists completion progress and the current step in text below it. I think that it would be useful to expose a bit of what's happening to users even if it is a bit technical so that they understand that this is really decentralized and that there's actually stuff going on here - not just our "system" being slow.

Thoughts?

Besides the specifics of the status page, it sounds like we're good to go to build out a quick and dirty implementation of this tomorrow.

**Comment by shea256** [comment] 2017-08-03 21:11
Yeah agreed @larrysalibra. I do believe there's a hybrid solution here or some other clever way of displaying the information. I'll think more about it. Also @guylepage3 may have thoughts on this.

**Comment by guylepage3** [comment] 2017-08-03 21:33
>The problem i was trying to solve is that there are ~8 different states in the name purchase process for a regular (non-subdomain name) and it's hard to provide much in the way of information about which steps have completed versus which are remaining.

@larrysalibra can we somehow reduce the amount of states that the user sees? I feel as though the user does not need to know "all" of the complexity that is going on in the background but just needs to be aware of a) certain crucial states that could break the registration process. I transferred some BTC yesterday from one wallet to another and they told me that the process will take longer than usual which was 7 confirmations. I don't need to see all 7 confirmation states but i just need to know why it will take longer and provide me with a time estimate.

I'm thinking we can reduce the number of states that the user sees to 4. Funding, preorder, register and update. And maybe we can get rid of "preorder" for the user as well reducing it down to 3 steps that the user sees.

Thoughts?

**Comment by larrysalibra** [comment] 2017-08-04 10:16
I see the status page as:
* an opportunity to manage expectations: usernames take time to register. A number of time dependent steps need to occur to make a blockstack name secure and functional. This isn't just an insert into a mysql database.
* an opportunity to educate users who are interested about what is happening and link them over to the explorer so that they can see what's going on. This also serves to re-enforce the notion that blockstack is decentralized and that there really are no 3rd parties.

We currently have it simplified down to 2 states: registration pending and then ready to use. Users find this confusing in that names stay in pending for a very long time and it feels like nothing is happening. They don't know why the name is pending, all they know is that when picking a username in any other app on the internet works immediately.  For some reason usernames on Blockstack take a really long time. Is it broken? Is it just not working very well?

The approach most bitcoin walets take with this is to display a transaction and then either "unconfirmed" or the number of confirmations. We have a similar situation: 4 transactions (funding + 3 step registration) - each one has to be confirmed before the name can be used.

Another way to display this information is the in the form of a checklist.

**Comment by larrysalibra** [comment] 2017-08-04 10:18
@jackzampolin had some feedback on name registration (https://paper.dropbox.com/doc/Name-registration-Notes-2-Aug-17-CFykuYwOSrVOMW4V4G2nT) and mentioned links to explorer for each transaction. Jack, any thoughts on our design? (see the above thread)

**Comment by guylepage3** [comment] 2017-08-04 12:36
>I see the status page as:

>- an opportunity to manage expectations: usernames take time to register. A number of time dependent steps need to occur to make a blockstack name secure and functional. This isn't just an insert into a mysql database.
>- an opportunity to educate users who are interested about what is happening and link them over to the explorer so that they can see what's going on. This also serves to re-enforce the notion that blockstack is decentralized and that there really are no 3rd parties.

This is a fundamental issue with blockchain applications. A UX fundamental is, "do not punish the user for bad tech." By forcing them to go through this long process, we are not doing a good job of providing the best experience imo. We can simplify things a bit with a description of what is happening. I see "Providing a realistic estimated time" for each of the 4 states and a description of what is happening, sufficient enough for the user. I as a user do not care to learn about tech. Just get me my name as fast as possible. I still say this UX problem still lays in the hands of the engineers to not give up working to make this process faster and/or less painful for the user.

>We currently have it simplified down to 2 states: registration pending and then ready to use. Users find this confusing in that names stay in pending for a very long time and it feels like nothing is happening.

100%. That's because we went a bit to far on the simplification of this. by making the process **Funding**, **preorder**, **register** and **update**, we will add just the right amount of information for the user.

**Comment by larrysalibra** [comment] 2017-08-05 11:37
> One way to do this would be to have 4 circles that are slightly grayed when they have zero confirmations and then get progressively darker once they have been confirmed.

Hmmm - I'm not sure people would know what the shade meant. Darkening shades on their own don't really communicate progress to me. Another idea could be those round circles that apple uses for app store or music/video downloads:

<img width="21" alt="screen shot 2017-08-05 at 7 36 34 pm" src="https://user-images.githubusercontent.com/597182/28995207-795b54b8-7a15-11e7-954f-09d745483ac9.png">

We could make them a bit bigger and after step completes put a check box in the middle to indicate completion.

**Comment by guylepage3** [comment] 2017-08-05 16:24
>Hmmm - I'm not sure people would know what the shade meant. Darkening shades on their own don't really communicate progress to me.

I don't think a color indicates progress actually. but clear and obvious steps indicating that progress is happening works. Also multi-color is a step outside our brand. I am in agreement with @shea256 on this one that a simple shade or highlight color, being one color or shade, will suffice.

**Comment by guylepage3** [comment] 2017-08-17 15:09
Implementation issue is here.. https://github.com/blockstack/blockstack-browser/issues/669

Closing issue.

**Closed by guylepage3** 2017-08-17 15:09 UTC
Labels: enhancement
