### ISSUE TITLE
Add validation for periods in Blockstack ID

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#955] opened 2017-10-24 20:58 UTC
We have a user who tried to register a name with a period in it: `foo.bar.id`. This resulted in the browser issuing a `NAME_PREORDER` that contained a malformed name. When the `NAME_REVEAL/NAME_TRANSFER` was issued it was rejected as malformed.

We should add a client side validation to check that the `bar.id` exists and is owned by the wallet before registering `foo.bar.id`

@kantai @larrysalibra @yknl

**Comment by larrysalibra** [comment] 2017-10-25 12:58
We don't support registering subdomains. Neither the browser nor core should be processing names like `foo.bar.id` - what might have happened on the browser side is that when disabling subdomains a bug was introduced. I'll look in to this on browser. 


Thanks for reporting this @jackzampolin !

**Comment by larrysalibra** [comment] 2017-10-25 14:33
@jackzampolin I'm unable to replicate this in the browser. 

The search for username box doesn't allow the user to enter periods. It searches for available usernames in the enabled namespaces (currently only `.id` in the browser).

If the user tried to modify the address bar url manually by changing http://localhost:3000/profiles/i/add-username/0/select/bar.id to http://localhost:3000/profiles/i/add-username/0/select/foo.bar.id, they get redirected back to http://localhost:3000/profiles/i/add-username/0/search.

Can you provide more information as to how the user did this?

**Comment by larrysalibra** [comment] 2018-01-17 12:54
Closing this because of inability to reproduce the problem. If you have steps that can be followed to replicate the problem, please re-open!

**Closed by larrysalibra** 2018-01-17 12:54 UTC
Labels: bug
