### ISSUE TITLE
Users with zonefiles and non-standard profile paths (with no such profile written) cannot write to profile

### ISSUE THREAD

**Issue by prabhaav** [blockstack/blockstack-browser#1717] opened 2018-10-24 17:03 UTC
See: https://github.com/blockstack/blockstack-core/issues/875

The profile provided for Blockstack ID naval.id features a zonefile URL that cannot be loaded, blocking this user's access to GAIA storage. Go to https://core.blockstack.org/v1/names/naval.id and try to load the zonefile URL provided (https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/0/profile.json). It returns a BlobNotFound.

The problem can also be seen when trying to use GAIA gateway, https://gaia-gateway.com/naval.id/www.stealthy.im/pk.txt, which returns: {"error":"Failed to load profile for naval.id"}.

The search endpoint won't even return a result for user naval.id: https://core.blockstack.org/v1/search?query=naval. It only returns one result for a different user "navaladi.id.blockstack".

We are seeing a variety of different behaviors for other important Blockstack user IDs as well, where the following behavior legend applies:

X - doesn't find
O - finds
D - downloads the profile

naval.id:
  - https://core.blockstack.org/v1/names/naval.id
  X https://gaia-gateway.com/naval.id
  X https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/0/profile.json
  O https://gaia.blockstack.org/hub/19rJSaipwUdFwS5iD7yMvAvtAYGA36fTDS/profile.json

fred.id
  - https://core.blockstack.org/v1/names/fred.id
  O https://gaia-gateway.com/fred.id
  O https://gaia.blockstack.org/hub/1CER5u4QXuqffHjHKrU76iMCsqtJLM5VHu/0/profile.json
  X https://gaia.blockstack.org/hub/1CER5u4QXuqffHjHKrU76iMCsqtJLM5VHu/profile.json

fredwilson.id
  - https://core.blockstack.org/v1/names/fredwilson.id
  X https://gaia-gateway.com/fredwilson.id
  D https://gaia.blockstack.org/hub/1GSFLzRi4BzC4iQKDHypAfC5e4esYeM7DK/0/profile.json
  X https://gaia.blockstack.org/hub/1GSFLzRi4BzC4iQKDHypAfC5e4esYeM7DK/profile.json

werner.id
  - https://core.blockstack.org/v1/names/werner.id
  X https://gaia-gateway.com/werner.id
  X https://gaia.blockstack.org/hub/1DGwhkq2hJuMNn8QWYUXtbeqtkZc4Wpdac/0/profile.json
  X https://gaia.blockstack.org/hub/1DGwhkq2hJuMNn8QWYUXtbeqtkZc4Wpdac/profile.json

barrysilbert.id
  - https://core.blockstack.org/v1/names/barrysilbert.id
  O https://gaia-gateway.com/barrysilbert.id
  D https://gaia.blockstack.org/hub/1JzruCrL17GEByT3FwqSHD5i93eK9HU9S5/0/profile.json
  X https://gaia.blockstack.org/hub/1JzruCrL17GEByT3FwqSHD5i93eK9HU9S5/profile.json

**Comment by kantai** [comment] 2018-10-24 17:23
So for a couple of those -- this issue is just the user never logged into the browser after initiating a transfer out of onename (`werner.id` and `fredwilson.id`).

A few of those seem to be working fine (`barrysilbert.id` and `fred.id`):

https://core.blockstack.org/v1/users/fred.id
https://core.blockstack.org/v1/users/barrysilbert.id

`naval.id` doesn't seem to be working correctly:

https://core.blockstack.org/v1/users/naval.id

His browser _should_ have written the profile to the correct location when his account was restored / attempted sign in with the application. But I understand that you reported that it is not the case.

Where did the error occur? Was it during the app sign in, and the log in screen just loaded forever and couldn't sign in after he approved the sign in?

**Comment by kantai** [comment] 2018-10-24 17:29
I see -- so the login flow completed? That's helpful for running down the bug.

**Comment by hstove** [comment] 2018-10-24 17:30
@prabhaav can you indicate whether Naval had already signed in to Stealthy in months past? Or was this the first time?

**Comment by prabhaav** [comment] 2018-10-24 17:31
This was his first time using Stealthy.

**Comment by kantai** [comment] 2018-10-24 17:56
Cool -- I just replicated this with `blankstein.id` by blowing away my profile object. Will provide more relevant details soon.

**Comment by yknl** [comment] 2018-10-24 19:12
Thanks for submitting a PR for a fix so quickly @kantai 
> This kind of specific bad behavior can be fixed during the restore by catching the profile lookup exception, and storing the zonefile with a default profile. Opening a PR, and renaming this issue so that it's a bit more clear what's going on. We probably would want to do something a little more than just fix this restore behavior (i.e., on restore, if the profile is empty, just go ahead and write the default profile, or try to find an old profile location and copy it over), but I'll leave that up to someone on the Browser team to decide.

I think we might want to provide a real fix for this in blockstack.js. (i.e. Writing the default profile on restore when this specific situation is detected) The reason being the Blockstack browser might not be the only authentication provider in the future and other developers are likely to run into the same problem. These old faulty names are going to exist for a very long time until eventually all of them have been fixed. The downside is that it might add bloat to the blockstack.js library.

**Comment by markmhx** [comment] 2018-10-30 10:00
@kantai Has the merged fix for this been tested manually with Stealthy and confirmed to work?

**Comment by kantai** [comment] 2018-11-28 16:10
This patch was released in v0.34.2 -- closing this issue for now. If this continues to be a problem, we can reopen.

**Closed by kantai** 2018-11-28 16:10 UTC
