### ISSUE TITLE
Registering a Sponsored Name Results in an Empty Profile and Inability to Log In

### ISSUE THREAD

**Issue by jehunter5811** [blockstack/blockstack-browser#1767] opened 2019-01-02 11:50 UTC
It appears as if the flip to the new year caused a new bug with the name registrar/browser? This just started yesterday as far as I can tell, but registering a new sponsored name will result in an empty profile and an inability to log into apps. 

This has been verified by myself and Nick from Blockusign.

**Comment by hstove** [comment] 2019-01-02 13:40
Can you elaborate a bit more on the issue here? I just created a new subdomain (successfully), then logged into Graphite, and its working fine for me. My localStorage in graphite looks normal.

**Comment by hstove** [comment] 2019-01-02 13:53
I just did some testing:

- broken on local browser w/ Brave
- works on local browser w/ Chrome
- works on hosted browser w/ Brave

**Comment by jehunter5811** [comment] 2019-01-02 15:30
@hstove I just tried registering a subdomain id in Firefox and got this error: 

<img width="1407" alt="screen shot 2019-01-02 at 8 37 23 am" src="https://user-images.githubusercontent.com/10519834/50598625-e6a1cc00-0e70-11e9-9c65-39d637384934.png">

Before that, it seemed I was able to register a subdomain name, but when looking at the localStorage object, the profile looked like this: 

```
{"@type":"Person","@context":"http://schema.org"}
```

It was missing everything else. I tried the name registration again to confirm and that's when I got the registration error you see in that screenshot.

**Comment by markmhx** [comment] 2019-01-04 14:54
Here's what I'm seeing in local storage for the profile property upon redirect back to the app after registering a new subdomain name:

<img width="1708" alt="screen shot 2019-01-04 at 15 52 51" src="https://user-images.githubusercontent.com/28991/50694003-fcfa8400-1038-11e9-8ffe-54ef57808500.png">

**Comment by jehunter5811** [comment] 2019-01-09 14:51
This appears to be working as expected now! Just tested with both a name registered through the default hub and one registered on a custom hub. Unless you all need to look into anything else, I think this can be closed.

**Comment by markmhx** [comment] 2019-01-09 15:11
@jehunter5811 That's great! Please let us know if it arises again.

**Comment by hstove** [comment] 2019-01-11 18:06
I think I ran into Nick's issue last night as well, inadvertently. It appears that when you first sign up and are auth'ing into a multi-player app, we don't update the profile to include the apps object. It does work successfully the second time you auth.

**Comment by hstove** [comment] 2019-01-23 19:44
I'm going to close this because I haven't been able to reproduce the issue in our current build on develop.

I was investigating the potential for a first-time login to not have a properly set up profile.json. After trying multiple sign-up situations, including from a multi-player auth flow, everything seems to be normal. I'm moving it into QA so that we can confirm when we publish a beta build, and then potentially close.

**Closed** 2019-02-05 18:06 UTC
Labels: bug
