### ISSUE TITLE
Ensure error message shown when password incorrect during sign in

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack-browser#1849] opened 2019-02-25 18:28 UTC
Can't restore/login with certain magic codes in the browser. Have tested multiple codes and only applies to some. 

macOS-v0.35.4
Chrome
Upgraded from previous version

To reproduce: 
• Click `Sign in with an existing ID`
• Enter specific testing magic code (ask @jeffdomke) 
• Click `Sign in`
• Enter specific testing password (ask @jeffdomke) 
• Click `Next`
• Browser appears unresponsive/nothing happens

Expected: 
• ID restores

**Comment by hstove** [comment] 2019-02-25 18:32
Console errors? My first assumption is that it's an invalid password.

**Comment by aulneau** [comment] 2019-02-26 14:45
if you have the codes available, we should check them out. I tested one directly from the browser, and then the ones from the emails I've gotten. They all worked.

**Comment by markmhx** [comment] 2019-02-26 19:59
I think @jasperjansz just recreated this live for me as well

**Comment by markmhx** [comment] 2019-02-26 20:00
@jeffdomke also mentioned in person that the latest thinking here in his case (and perhaps Jasper's as well) is that the passwords are wrong but we aren't showing an error message explaining that for some reason.

Should we retitle this to "Show error message when password entry wrong during sign in" or something to that effect?

**Comment by zone117x** [comment] 2019-03-04 17:56
I can reproduce this with the current release but it appears to be fixed in the develop branch. I think this was caused by a state transition race condition bug, which was fixed by this commit: https://github.com/blockstack/blockstack-browser/commit/1e6be2cd6c73cf9b91a7a668fdb67c7fa0a64bde

**Closed** 2019-03-04 18:11 UTC
Labels: bug
