### ISSUE TITLE
Browser doesn't load on macOS

### ISSUE THREAD

**Issue by BryanG1** [blockstack/blockstack-browser#1169] opened 2018-01-16 19:24 UTC
I'm on MacOS (access through Chrome) and and iOS (through Safari). The application on my mac doesn't load so I've needed to navigate directly through my browser to access the Blockstack browser.

**Comment by larrysalibra** [comment] 2018-01-17 14:12
I'm so sorry you're having trouble @BryanG1 - can you give me some more details about your computer? Which version of macOS are you using? What happens when you try to run the app?

**Comment by BryanG1** [comment] 2018-01-17 23:59
Hey there - see below. When I click the app icon nothing happens..

**Comment by wbobeirne** [comment] 2018-08-02 15:31
I think a screenshot was intended to be attached, but didn't come through. Closing this as needs information, feel free to reopen if you can still reproduce this.

**Closed by wbobeirne** 2018-08-02 15:31 UTC
