### ISSUE TITLE
BTC not appearing in my Blockstack wallet

### ISSUE THREAD

**Issue by nialljenIT365** [blockstack/blockstack-browser#1748] opened 2018-12-12 16:47 UTC
Apologies if this has been answered elsewhere.

I have sent a small amount of BTC but not appearing in my Blockstack browser wallet

I can see it in the wallet:
http://live.blockcypher.com/btc/address/1L95sumPifcdsoYm3iyyTxDQ8ZGHF4JYUS 

Balance remains zero on both Windows Desktop and Web browser.

Was hoping it would resolve itself but it has been a few days now.

Any assistance or advice appreciated.

**Comment by selfagency** [comment] 2018-12-12 17:15
+1

Having the same exact issue.

Here's the transaction: http://bit.ly/2QQfLvQ
Here's my wallet: http://bit.ly/2SKtHVD

Four days after sending it's still empty.

**Comment by ferrucc-io** [comment] 2018-12-18 07:01
Having this exact problem
![screen shot 2018-12-18 at 07 59 03](https://user-images.githubusercontent.com/8315559/50137314-1c548b80-029b-11e9-9ff6-7317ebd4cec1.png)
![screen shot 2018-12-18 at 07 59 18](https://user-images.githubusercontent.com/8315559/50137319-2080a900-029b-11e9-8f3e-f29a0a848426.png)

**Comment by moxiegirl** [comment] 2018-12-19 20:10
@nialljenIT365 @selfagency @ferrucc-io thanks for watching this issue.  A change was merged and should go live soon. Please look for an announcement in our [forum](https://forum.blockstack.org/.)

**Comment by hstove** [comment] 2018-12-20 21:37
Hey folks. We just pushed [version 0.35.0](https://github.com/blockstack/blockstack-browser/releases/tag/v0.35.0) with a fix for this.

Sorry for the issue! Thanks for bringing it up.

**Closed by hstove** 2018-12-20 21:37 UTC

**Comment by selfagency** [comment] 2018-12-20 21:41
To where did you push it, because I just downloaded a new version of the app and it's still 0.34.1 and my wallet is still empty.

**Comment by hstove** [comment] 2018-12-20 21:42
Did you download it from here? - https://github.com/blockstack/blockstack-browser/releases/tag/v0.35.0

We're almost done updating blockstack.org with the correct links.

**Comment by selfagency** [comment] 2018-12-20 21:45
Oh great, now instead of my money not appearing, my entire wallet doesn't appear.
![screenshot 2018-12-20 16 44 08](https://user-images.githubusercontent.com/2541728/50312517-98ef9180-0476-11e9-9921-c421d63a88b6.png)

**Comment by hstove** [comment] 2018-12-20 21:45
Can you send any Javascript errors you see in the console?

**Comment by selfagency** [comment] 2018-12-20 21:46
```
TypeError: "A.split(...)[1] is undefined"
	fetch http://localhost:8888/static/js/main.588ba25d4cd0cc1b5422.chunk.js:1:1722266
	refreshBalances http://localhost:8888/static/js/main.588ba25d4cd0cc1b5422.chunk.js:1:1535425
	refreshBalances http://localhost:8888/static/js/main.588ba25d4cd0cc1b5422.chunk.js:1:1535350
	n http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:175:77411
	g http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:175:81162
	componentDidMount http://localhost:8888/static/js/ReceivePage~SendPage.b5bd821f5f30d9634aa8.chunk.js:1:814
	Is http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:88844
	Cs http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:84218
	As http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:83719
	Es http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:82798
	Zi http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:81713
	enqueueSetState http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:147:47372
	setState http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:175:1689
	t http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:155:6976
	_loadModule http://localhost:8888/static/js/vendors.c906105d01124d927cb2.chunk.js:155:7085
vendors.c906105d01124d927cb2.chunk.js:147:66319
```

**Comment by hstove** [comment] 2018-12-20 21:51
Dang, I'm really sorry to see this. I'm having trouble reproducing right now. Can you try reseting the browser, restoring with your secret key, and seeing if the error persists?

**Comment by hstove** [comment] 2018-12-21 02:35
hey @selfagency , we made version 0.35.1 with a hotfix for this issue. You can download it on our [releases page](https://github.com/blockstack/blockstack-browser/releases). Once again, I'm really sorry about this!

**Comment by selfagency** [comment] 2018-12-21 02:44
@hstove Thanks, it's working now. I appreciate your responsiveness.
