### ISSUE TITLE
State update path breaks login (white screen of death)

### ISSUE THREAD

**Issue by odinho** [blockstack/blockstack-browser#1290] opened 2018-04-18 19:47 UTC
Steps:
- have 'old' browser.blockstack.org profile (not quite sure how to get this now without setting it up myself)
- used 'login with blockstack' on https://contribute.blockstack.org
- it redirected to https://browser.blockstack.org/?authRequest=... as expected
- but when page is loaded it goes to /update
- page is white, crash in console on `token.split('.')` IIRC (cannot do split on undefined)

#1282 @kantai 

Sorry about the sparse bug report. I went directly to browser.blockstack.org and updated successfully before I thought to report the bug.
I have a manual blockstack protocol handler, so might not be relevant for other users. In that case ignore.

**Comment by kantai** [comment] 2018-04-18 19:51
Thanks for reporting this @odinho -- this is likely true for all `update` paths whether it's browser.blockstack.org or the local version of the browser, e.g., localhost:8888

I'll look into reproducing with other authRequests as well.

**Comment by larrysalibra** [comment] 2018-04-19 09:01
I just ran into this problem too while working on the android SDK.

**Comment by markmhx** [comment] 2019-03-20 13:17
Any of you three able to reproduce this bug in 2019?

**Comment by larrysalibra** [comment] 2019-03-20 14:19
I haven't seen this in a long time.

**Comment by markmhx** [comment] 2019-04-09 16:13
We should update the version of blockstack.js integrated into https://contribute.blockstack.org/login

**Comment by markmhx** [comment] 2019-04-09 16:13
I'm closing this issue out since we believe we've fixed the token split error originally reported.

**Closed by markmhx** 2019-04-09 16:13 UTC
Labels: bug
