### ISSUE TITLE
Mac Doesn't Save Data

### ISSUE THREAD

**Issue by shane1900** [blockstack/blockstack-browser#916] opened 2017-10-14 00:35 UTC
Hi,

Newly installed on High Sierra.  It takes a very long time (several minutes to never) to open apps and when I am able to enter data such as in the to do list it never saves.  Hitting refresh starts over.  Any suggestions?

Thank you.

**Comment by larrysalibra** [comment] 2017-10-14 04:57
Which storage provider are you using?

**Comment by shane1900** [comment] 2017-10-14 13:44
Hi Larry.  The standard free.  In storage options I'm not able to click on any of the other options.

**Comment by shane1900** [comment] 2017-11-02 16:47
I reinstalled and it's working a bit better but now http://localhost:8888/profiles doesn't appear, it's blank.  I was wanting to buy a username.  Storage providers still are all greyed out.

**Comment by wbobeirne** [comment] 2018-08-02 14:57
That issue looks a lot like what happens in #1537, so I'm going to close this to consolidate on that one since it's reproducible.

**Closed by wbobeirne** 2018-08-02 14:57 UTC
