### ISSUE TITLE
Wallet: USD amount calculated incorrectly and BTC amount is wrong

### ISSUE THREAD

**Issue by plus-x** [blockstack/blockstack-browser#1174] opened 2018-01-18 02:20 UTC
**Description**

When looking at my wallet, the available BTC is wrong:
My available BTC shows 0.002993
But actual available is 0.0029925
It is off by 0.0000005

My wallet [at blockchain.info](https://blockchain.info/address/17xzDqGt9y2WNwZMNq6182E1BsEdN8N9kR)

Also the USD amount shows as $2.99. It seems to be multiplying the BTC value by 100 and just displaying that as the dollar amount. Should be about $34 @ today's rate. (See screenshot below)

**System Info**

- Mac OS X 10.13.2
- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Blockstack version 0.22.1 (installed from official installer package)
- Also tested on earlier Blockstack versions

**Steps to reproduce:**

1. With latest Blockstack installed, launch it fresh
2. Go to your wallet via the menubar icon
3. The web browser should open at URL: http://localhost:8888/wallet/receive#coreAPIPassword=off&logServerPort=off
4. View wrong USD amount. View wrong BTC amount (screenshot included)
5. Verify correct BTC amount [at blockchain.info](https://blockchain.info/address/17xzDqGt9y2WNwZMNq6182E1BsEdN8N9kR)
6. Verify correct USD amount [with Google](https://www.google.com/search?q=0.0029925+btc+to+usd)

![screen](https://user-images.githubusercontent.com/6692678/35077498-c1292ff6-fc0e-11e7-9d3c-1967dc29ffe1.png)

**Comment by larrysalibra** [comment] 2018-01-18 10:40
Hi @plus-x ! Thank you so much for the great bug report!

> When looking at my wallet, the available BTC is wrong:
My available BTC shows 0.002993
But actual available is 0.0029925
It is off by 0.0000005

The displayed BTC amount is rounded - you can see the exact amount by holding your mouse over the number.

This might be a good argument for using different units in our wallet: https://github.com/blockstack/blockstack-browser/issues/613

---

> Also the USD amount shows as $2.99. It seems to be multiplying the BTC value by 100 and just displaying that as the dollar amount. Should be about $34 @ today's rate. (See screenshot below)

That doesn't look right. We use bitstamp's btc to usd api for the exchange rate. 
https://www.bitstamp.net/api/v2/ticker/btcusd/

The wallet is calculating the usd value of my bitcoin properly for me - it could be that bitstamp's api was down or returning nonsense values. Can you let me know if the problem is still happening?

**Comment by plus-x** [comment] 2018-01-19 08:27
Nope, still happening for me.

Copy and paste from my Wallet:

Balance
0.002993 BTC
$2.99 USD

**Comment by wbobeirne** [comment] 2018-08-02 15:33
Closing as unable to reproduce. It's likely that the request to the price API was somehow failing, and falling back on the default hardcoded USD value (which is very, very out of date.)

**Closed by wbobeirne** 2018-08-02 15:33 UTC
Labels: bug
