### ISSUE TITLE
Add QR code functionality

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1498] opened 2018-07-03 19:11 UTC

**Comment by wbobeirne** [comment] 2018-08-14 15:10
Have we figured out what this flow is supposed to look like yet? I know we've discussed QR codes a lot, but I haven't seen any proposed implementations.

**Comment by jeffdomke** [comment] 2018-08-14 15:18
Yeah, we did some testing with a lib back during the initial on boarding project. @aulneau can explain more.

**Comment by jeffdomke** [comment] 2018-08-14 15:26
@aulneau worth salvaging the work robin did?

**Comment by aulneau** [comment] 2018-08-14 15:33
@wbobeirne this is the work Jeff is referencing -> https://github.com/robincwillis/blockstack-qr-demo feel free to take a look!

**Comment by wbobeirne** [comment] 2018-08-14 17:40
Sweet, thanks for the links.

> https://github.com/JodusNodus/react-qr-reader

+1 have used this before, performance is great and it's quite easy to set up. Paired with https://github.com/zpao/qrcode.react or something to generate the QR codes client side should be good.

I see that design shows the input field, but where would we expect a user to back up the QR code? Where should we have them go on an existing login to see it?

> https://github.com/robincwillis/blockstack-qr-demo

The above demo uses a server for generating QR codes which we definitely can't do, since this will contain the user's private key (Even if it's encrypted, still not something we want to do.)

**Comment by wbobeirne** [comment] 2018-08-21 14:30
@jeffdomke at some point if you could look at #1620 and let me know if you have any suggested changes, or ideas of how we can better provide users with QR codes / explain to them where to find them, that'd be excellent. The issue is marked `WIP`, but that's more from a UX perspective, not an engineering one.

**Comment by markmhx** [comment] 2019-03-19 16:16
I'm closing this out since it was addressed with https://github.com/blockstack/blockstack-browser/pull/1620

**Closed by markmhx** 2019-03-19 16:16 UTC
