### ISSUE TITLE
Ensure user is routed back to browser instead of system default during authentication

### ISSUE THREAD

**Issue by aviaryan** [blockstack/blockstack-browser#1759] opened 2018-12-22 07:11 UTC
I just got an email from a user of [yournote.app](https://yournote.app) saying

> When I click on green sign in button nothing happens. Just presses then nothing. I am using latest Firefox 64 and even tried with adblocker turned off.

I tried it on my computer as well and since I use local Blockstack Browser, Sign in button opened the link in the default browser (which is Chrome) and then redirected it back to Chrome. So, trying to login in Firefox actually logged me in, in Chrome.

So, there are 2 issues here -
1. Blockstack sign in button doesn't work for someone who has Firefox as default browser
2. Sign in on Firefox works incorrectly for someone who is not using Firefox as the default browser

Thanks.

> [Cross-posted from this forum topic](https://forum.blockstack.org/t/issue-with-firefox-sign-in/7012)

**Comment by jfacoustic** [comment] 2019-01-02 20:08
Any updates on this?  I was able to reproduce it as well.

**Comment by markmhx** [comment] 2019-01-02 20:14
I believe there are two scenarios here:

1. If the desktop Firefox user does *not* have the Blockstack Browser installed locally (and therefore needs to use the hosted browser at browser.blockstack.org), Firefox fails to redirect the user to the hosted browser and simply does nothing (aka "When I click on green sign in button nothing happens"). This issue is being tracked with https://github.com/blockstack/blockstack.js/issues/558 and I believe the best interim solution on the app developer's end may be to detect the user agent and guide any desktop Firefox users to download the Blockstack Browser locally or use Chrome, etc. to access the app with the hosted browser.

2. If the desktop Firefox user *does* have the Blockstack Browser installed locally but it's *not* set as the computer's default browser, then they'll be directed into Chrome or whatever browser is the default browser to authenticate with it. The only way I know of preventing this browser-changing behavior is setting the default browser to Firefox (h/t @jehunter5811). I'll open an issue (or see if we have an existing one) to see if we can prevent this behavior regardless of the default browser setting.

**Comment by markmhx** [comment] 2019-01-07 11:58
Thanks for the report @alextibbles. I'm assigning this issue over to @zone117x since he's actively working on browser support at the moment. 

@zone117x You're already working on the first scenario I listed above over at https://github.com/blockstack/blockstack.js/issues/558, so I'm changing this issue's title to reflect the second scenario. 

Do you think there's anything we can do with this second scenario insofar as ensuring that the user is routed back to the browser they used to initiate auth, regardless of the system's default browser setting (e.g. with a parameter)?

**Comment by markmhx** [comment] 2019-01-07 12:01
@alextibbles To be clear about your report, do you mean that when you click the button to authenticate, you see an "Open xdg-open?" dialog but upon assenting, nothing happens i.e. the protocol isn't handled by Firefox at all?

**Comment by zone117x** [comment] 2019-01-07 14:34
> Ensure user is routed back to browser instead of system default during authentication

In order for this to be possible the following criteria must be met:
* All operating systems give the launched protocol handler (Blockstack Browser app) the identity (like the full executable path) of the initiating application (examples: `/Applications/Firefox.app`, `C:\Program Files\Google\chrome.exe`, etc..)
* All browsers provide a command line option to open a new tab (example: `C:\Program Files\Google\chrome.exe --open-tab https://test.com`

My gut feeling is that this is probably possible on some operating systems and some browsers, but unlikely possible for all. 

This new protocol detection method https://github.com/blockstack/blockstack.js/pull/591 does not prevent the default system browser from being opened, but it does allow the browser being used to detect a protocol handler failure and redirects the user to the https web auth.

**Comment by markmhx** [comment] 2019-01-28 15:03
@zone117x  I've added this to the new sprint with your assignment

**Comment by dantrevino** [comment] 2019-02-07 05:18
I'm not sure what "routed back to browser instead of system default" means, but during testing, I've had users who chose *not* to give permissions for "Basic Info" get routed back to blockstack browser, rather than the app landing page.  This caused confusion with the user confusing the Blockstack Browser with NoteRiot (in my case).  

i.e. the current flow of:
app landing page -> auth -> auth fail -> blockstack browser

should maybe be:
app landing page -> auth -> auth fail -> app landing page

Or at least maybe a message to the user indicating that they're being redirected to the Blockstack Browser, *not* <App Name>

/cc: @moxiegirl @jeffdomke

**Comment by hstove** [comment] 2019-02-07 06:58
Good catch @dantrevino , and we are tracking that issue, I think #1727 is one of them. But this scenario is different:

(Imagine Brave is my default browser, and I have the native app installed)

- View blockstack app in Chrome
- Click 'sign in with blockstack'
- I get redirected to Brave, which I wasn't using
- Sign in
- I redirect back to the Blockstack app, but still in Brave, where I didn't start

**Comment by jeffdomke** [comment] 2019-02-07 17:03
For the issue Hank describes, not sure how frequent this problem is or if we should even worry about it. All kinds of weird stuff can happen users are using their non-default browser and expect state from the default one to be there. I guess I'm saying I expect this is a problem for any client app that loads a webview, like Slack for example. Are there any easy answers?

**Comment by markmhx** [comment] 2019-02-12 13:13
I agree this issue's problem may not be easily solvable, at least not in a way that makes it worthwhile.

@zone117x did / do you have any active ideas for how to tackle it? I vaguely remember a conversation in which you thought there was a possible technique. But if not, agree we should just close this out?

**Comment by zone117x** [comment] 2019-02-12 20:04
@markmhx Ended up just implementing this for MacOS while testing if it was possible. MacOS was quick and easy, but Windows will take some time to investigate. I think Windows support for this should be iceboxed.

**Comment by markmhx** [comment] 2019-02-13 15:27
@zone117x Awesome! And sounds good re: just tackling MacOS for now.

**Closed** 2019-02-14 22:03 UTC
Labels: bug, protocol-handling
