### ISSUE TITLE
username is not immediately available when restoring an ID

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack-browser#1355] opened 2018-05-16 22:51 UTC
When restoring an ID via 12 word phrase or encrypted hash, sometimes the username is not immediately available. I am not exactly sure why, but if we can't fix this we'll need to consider an alt design for displaying the success screen after restoring your ID

**Comment by aulneau** [comment] 2018-05-21 20:30
@yknl it seems as though this might also be in a few other places:
![screen shot 2018-05-21 at 3 29 21 pm](https://user-images.githubusercontent.com/11803153/40328404-dbdb1efa-5d0b-11e8-9254-3a3e3e661625.png)

the other IDs are ones I had just made, I am not sure why only one ID would have a username and the others would not.

**Comment by yknl** [comment] 2018-05-21 21:11
@aulneau are the other usernames recently registered? As in the last 4 hours? Currently we do not have a way of looking up usernames that haven't propagated on the network. So if the user restored before the usernames were confirmed, they wouldn't show up.

**Comment by yknl** [comment] 2018-06-20 19:52
![image](https://user-images.githubusercontent.com/29081231/41681235-fb20ce38-74a1-11e8-84f0-e283ec93077e.png)

**Comment by aulneau** [comment] 2018-06-21 16:01
should be fixed with https://github.com/blockstack/blockstack-browser/commit/7cdbc12d1892f7a53c4637092f6906d33cd944e9

**Comment by aulneau** [comment] 2018-06-21 16:08
<img width="503" alt="screen shot 2018-06-21 at 11 08 08 am" src="https://user-images.githubusercontent.com/11803153/41731208-68335922-7543-11e8-90f8-9f9d2ba6e1de.png">

**Comment by markmhx** [comment] 2019-03-20 13:14
I'm closing this out since it appears to have been addressed with the above PR and @petec029 given the timing of your report, it's possible you were using a version of the browser before the fix was made.

Please re-open, however, if you or anyone else is still experiencing this in the latest version of the browser.

**Closed by markmhx** 2019-03-20 13:14 UTC
Labels: bug
