### ISSUE TITLE
unable to buy a username with windows install

### ISSUE THREAD

**Issue by alidcastano** [blockstack/blockstack-browser#914] opened 2017-10-13 22:35 UTC
similar to #875, the application gets hung up on buying a domain and does not proceed to next step

There are no errors on the console.

**Comment by chadyj** [comment] 2017-10-25 23:05
Could be a dupe of https://github.com/blockstack/blockstack-browser/issues/962

**Comment by wbobeirne** [comment] 2018-08-02 14:56
I'm closing this issue as stale as there's not much to go off of here, and there haven't been any other reports of this since. Feel free to reopen if you can reliably reproduce. Sorry about that!

**Closed by wbobeirne** 2018-08-02 14:56 UTC
