### ISSUE TITLE
Daily name registration 6/26-6/30

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-browser#555] opened 2017-06-26 18:50 UTC
This week, each member of the core team is actively registering new names for ourselves daily to test registration. 

Each day, we'll add our newly registered name in a comment below, along with a description of errors experienced and the total cost. We will refund your expenses at the end of the week.

**Comment by guylepage3** [comment] 2017-06-26 22:01
My shot at it today...
- [#557: full on-boarding/ register a name use case](https://github.com/blockstack/blockstack-browser/issues/557)

**Comment by pstan26** [comment] 2017-06-27 04:45
6/26
Saw `add username` button on my throwaway account and clicked it. Brought me to name registry.
![screen shot 2017-06-27 at 12 32 14 am](https://user-images.githubusercontent.com/5605552/27571053-deccaa86-5ad0-11e7-8e4c-c5a5f412d802.png)

Without enough funds and with nothing stopping me by ways of message, I attempted to register patrickwstanley.id
![screen shot 2017-06-27 at 12 31 58 am](https://user-images.githubusercontent.com/5605552/27571118-529fd2a8-5ad1-11e7-8327-ccff979cdf49.png)

It sent a request to the core which hung for over 15 seconds before I exited out. 

Next, mostly because I knew I needed to do this, I sent funds from my hardware wallet to my Blockstack wallet. Now waiting...
![screen shot 2017-06-27 at 12 33 14 am](https://user-images.githubusercontent.com/5605552/27571150-9765f070-5ad1-11e7-92d6-3b113986c99c.png).

I tried another name (while only holding .005 bitcoin). The screen suggested I only needed .001 more, which I don't yet know will be sufficient.
![screen shot 2017-06-27 at 12 35 35 am](https://user-images.githubusercontent.com/5605552/27571171-cd7c2b0c-5ad1-11e7-9acd-249e40d9c4ed.png)

**Comment by shea256** [comment] 2017-06-27 05:43
I tried today and failed. I'll post some more details on my experience.

**Comment by larrysalibra** [comment] 2017-06-27 12:11
I tried to registered the name `swimming.id` on the current release version of Blockstack on macOS v0.10.0 using the bundled version of the portal. I started with a clean state and 0.02 btc in my core wallet.

It’s working so far the `NAME_PREORDER` operation has been recognized on the network and the `NAME_REGISTRATION` op has been successfully broadcast and is in the process of being confirmed by the network. Will update this comment with the final result a bit later.

**Comment by kantai** [comment] 2017-06-27 12:40
I attempted to register yesterday from a clean slate by running the install
script in an Ubuntu clean VM. Installing portal failed because `npm
install` ran out of memory. Will be attempting on the Mac Mini today.

**Comment by guylepage3** [comment] 2017-06-27 15:28
Here's today's progress on my first name registration...

https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-311394671

**Comment by pstan26** [comment] 2017-06-27 19:18
6/27 SUCCESS! (thanks to sending bitcoin to my wallet yesterday)

Details here (TL;DR I now own docusign.id):
https://github.com/blockstack/blockstack-browser/issues/567

**Comment by kantai** [comment] 2017-06-27 19:46
Success on 6/27 -- using mac mini + the portal bundle from the mac release page. https://explorer.blockstack.org/name/ablankst_jun27_test.id

**Comment by guylepage3** [comment] 2017-06-28 21:45
Here's today's progress on my first name registration... **(Day 3)**
- [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-311801083)

**Comment by pstan26** [comment] 2017-06-28 21:55
No success. Couldn't click "+ create" button. it shows a circle with a cross that doesn't allow me to register. https://github.com/blockstack/blockstack-browser/issues/567

**Comment by guylepage3** [comment] 2017-06-29 18:38
Here's today's progress on my first name registration. (Day 3)

- [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-311801083)

**Comment by guylepage3** [comment] 2017-06-29 18:42
Here's today's progress on my first name registration... **(Day 3 of 4)**
- [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-312061936)

**Comment by kantai** [comment] 2017-06-29 18:44
6/29:

installed on a clean ubuntu VM from debs (both core and browser).

registration looks like it's going through:

https://explorer.blockstack.org/name/ablankst_testing_jun29.id

**Comment by guylepage3** [comment] 2017-07-03 14:44
Here's today's progress on my first name registration... **(Day 7 of 7)**
- [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-312663449)

**Comment by guylepage3** [comment] 2017-07-11 21:19
closing this out.

**Closed by guylepage3** 2017-07-11 21:19 UTC
