### ISSUE TITLE
Ensure that ID creation screen is fast across devices

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-browser#1900] opened 2019-04-05 18:13 UTC
Upon reviewing TryMyUI videos for App Mining participants in March 2019, we noticed that several users (especially on mobile devices) spent inordinate amount of times (over 10 seconds) waiting for the progress screen to finish during onboarding in which their ID is created.

This issue entails improving the speed of that screen so the user doesn't have to wait more than a few seconds.

**Comment by AcidLeroy** [comment] 2019-05-22 14:40
Not sure if this helps, but we noticed that we are failing on the last `hub_info` call and then we never get redirected to the app that requires the block stack id. I have a screenshot of the issue we encountered when running on an older iPhone (6) and attempt to sign up with blockstack after the user was directed away from our site to do so. They never end up getting redirected properly after they setup their account. 

![Screen Shot 2019-05-21 at 12 36 53 PM](https://user-images.githubusercontent.com/249048/58183480-a5b62280-7c6c-11e9-8515-31b8c2949761.png)

I've also included the screen that we seem to get stuck on forever after the hub_info call fails. 
![Image from iOS (1)](https://user-images.githubusercontent.com/249048/58183799-2bd26900-7c6d-11e9-8baf-2a50c24fa44f.jpg)

**Comment by markmhx** [comment] 2019-06-04 14:49
Upon discussion, we want to see first if https://github.com/blockstack/blockstack.js/pull/659 resolves this issue then proceed to consider other possible solutions if it doesn't.

**Comment by zone117x** [comment] 2019-06-04 17:54
Just left a comment about this in the referenced issue -- see https://github.com/blockstack/blockstack.js/pull/659#issuecomment-498774222

Cross posting some of the information to here..

----

I renamed the referenced issue to `[Experimental] ...` which more accurately reflects what this PR is. It's not currently in being worked on. However, some previous work related to this issue has recently made progress:
* bitcoinjs-lib tweaked their secp256k1 dependency structure in response to our [proposal](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1393) which makes some of the additional required work easier -- see [[1]](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1393#issuecomment-494647487), [[2]](https://github.com/bitcoinjs/bitcoinjs-lib/issues/1393#issuecomment-495077304).
* [PR merged](https://github.com/blockstack/blockstack.js/pull/652) updating blockstack.js to use bitcoinjs-v5 (lets us use the new capabilities referenced above). 

This PR would take significant more work to fully complete due to the `elliptic` and nodeJS crypto-browser-shim dependencies being so deeply integrated throughout this lib, bitcoin-js, Blockstack Browser, etc.. 

However, we could target something specific, like improving the performance of the Browser onboarding screen -- which is more reasonable to get done. 

I wrote up a detailed issue -- initially for e2e test flakiness -- but it almost exactly outlines these Browser problems. Just renamed it: https://github.com/blockstack/blockstack-browser/issues/1906

This is still a good next step towards tackling this:
> Profiling & testing needs done so we can identify and prioritize potential work...

**Comment by zone117x** [comment] 2019-06-04 18:25
To clarify what I think needs to be done:

The first step would be profiling & testing to determine what are the actual bottlenecks are in the onboarding process. This seems like QA/testing work. For example:
* Network IO - is this a major contributing factor? Is it asset size constraints or some API endpoint response latency? Which assets or API endpoints? 
* CPU & memory - at what level of hardware do either of these become a bottleneck? What pages & functions are culprits? 

These can almost all be tested, simulated, profiled, etc using Chrome developer tools, VMs, other web profiling tools & services. 

Once the bottlenecks are identified I can definitely help out with optimizing them, especially if it does turn out to be crypto-operation related. 

@hstove @timstackblock @markmhx thoughts?

**Comment by markmhx** [comment] 2019-06-05 10:20
Thanks @zone117x; profiling the bottlenecks thoroughly sounds like a good idea to me. @timstackblock do you want to take this on?

**Comment by timstackblock** [comment] 2019-06-06 19:49
Sure I can take a look @markmhx. 

Just to clarify the task at hand, we want to get an idea of how the current on-boarding experience is across several mobile devices. Then work on fixing this problem after we find the bottlenecks in our mobile on-boarding flow. Is this correct? 

Should I begin verifying the current mobile on-boarding flow and start logging defects?

**Comment by markmhx** [comment] 2019-06-07 11:15
Yep that's correct, but note that this issue and investigation specifically concerns just _performance_ bottlenecks (aka where in the onboarding flow things get really slow, say 3+ seconds, between transitions).

So yep, please do verify the current mobile flow (and desktop too, if you'd like – though mobile seems to be the reported culprit) and log bugs related to slowness where you see them.

Much thanks! 🙏

**Comment by timstackblock** [comment] 2019-06-17 14:44
1. Android mobile test run everything looks good with Chrome.

2. Android mobile test run has long timeouts in Firefox.

VIDEO OF THE ISSUE
https://screencast-o-matic.com/watch/cq1bIgTEkT

There is about a 60 second or more loading time for firefox between screens during onboarding. This is happening on multiple android devices you can use Galaxy 9 or Pixel 3 and the lag is consistent.

STEPS TO REPRODUCE:
Create a new ID for blockstack browser using firefox on an android device. This happens when creating a new blockstack ID after the user enters their password twice. The loading circle will continue to hang.

SCREENSHOT OF THE BUG
<img width="246" alt="Screen Shot 2019-06-17 at 10 39 53 AM" src="https://user-images.githubusercontent.com/49165468/59613166-6c969400-90ec-11e9-84e4-e84a23d1d105.png">

**Comment by timstackblock** [comment] 2019-06-17 14:57
1. Iphone mobile test run everything looks good with Chrome.

2. Iphone mobile test run has very long time outs for Safari

VIDEO OF THE ISSUE
https://screencast-o-matic.com/watch/cq1b2wTEEF

STEPS TO REPRODUCE
Create a new ID for blockstack browser using Safari on an Iphone. This happens when creating a new blockstack ID after the user enters their password twice. The loading circle will continue to hang.

There is about a 120 second or more loading time for safari between screens during onboarding. This is happening on multiple Iphone devices you can use IphoneXS with iOS12, Iphone 8 Plus with iOS11 and Iphone 7 with iOS 10 the lag is consistent.

This spinner seems to be infinite I cut it after about 4 minutes but it kept going.

SCREEN SHOT OF THE BUG
<img width="312" alt="Screen Shot 2019-06-17 at 10 56 05 AM" src="https://user-images.githubusercontent.com/49165468/59614331-8c2ebc00-90ee-11e9-950c-478c88a14513.png">

**Comment by timstackblock** [comment] 2019-06-18 12:40
See updated notes with a physical device in my hand as opposed to browserstack we still have an issue but the time is a bit more manageable.

**Comment by jeffdomke** [comment] 2019-08-22 19:36
Next steps: 
Testing network request performance: https://github.com/blockstack/blockstack-browser/issues/1948
https://github.com/blockstack/blockstack.js/issues/703
https://github.com/blockstack/blockstack.js/issues/691

**Closed** 2020-01-21 16:06 UTC
Labels: P2 bug, enhancement
