### ISSUE TITLE
ID format is too similar to BTC address

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-browser#1066] opened 2017-11-13 16:27 UTC
I know this is a long standing issue, but I've had a number of users making the mistake of sending money here or thinking that it is their wallet. A user I'm working with right now just requested a refund to that address. This is a common source of confusion.

**Comment by larrysalibra** [comment] 2017-11-13 16:58
+1

**Comment by shea256** [comment] 2017-11-14 06:13
+1 Let's brainstorm some solutions.

**Comment by vsund** [comment] 2017-11-14 10:00
What's about simply wrapping another encoding around? Like for example base64.

Although we have a limited input alphabet, `base64(address)` should look different enough, since Bitcoin addresses use base58. This also makes addresses longer. Base64 can contain `+` and `/` but I think with Bitcoin addresses as input we should never hit these bytes.
We should also be able to truncate the padding of `=` symbols (can add them again by knowing the length).

Example:
```
normal:    1GQxshrCoLk1QUAudFRtJk9Un6NVsu55W8
base64:    MUdReHNockNvTGsxUVVBdWRGUnRKazlVbjZOVnN1NTVXOA==
truncated: MUdReHNockNvTGsxUVVBdWRGUnRKazlVbjZOVnN1NTVXOA
```

**Comment by larrysalibra** [comment] 2018-01-17 13:42
This is a duplicate of #888 - let's continue the discussion over there!

**Closed by larrysalibra** 2018-01-17 13:42 UTC
